---
garage_install_all_users: false
garage_install_version: 2.3.0
garage_install_configuration:
  metadata_dir: /var/lib/garage/meta
  data_dir: /var/lib/garage/data
  db_engine: lmdb
  replication_factor: 1
  compression_level: 2
  rpc_bind_addr: "[::]:3901"
  rpc_public_addr: "127.0.0.1:3901"
  rpc_secret: "{{ garage_install_rpc_secret }}"
  s3_api:
    s3_region: garage
    api_bind_addr: "[::]:3900"
    root_domain: ".s3.garage"
  s3_web:
    bind_addr: "[::]:3902"
    root_domain: ".web.garage"
