---
- name: Define Configuration Variables
  ansible.builtin.set_fact:
    config_file: >-
      {{
        '/etc/garage.toml' if garage_install_all_users
        else (ansible_facts.env.HOME ~ '/.garage.toml')
      }}
    metadata_dir: >-
      {{
        garage_install_root_metadata_dir if garage_install_all_users
        else (ansible_facts.env.HOME ~ '/.garage/meta')
      }}
    data_dir: >-
      {{
        garage_install_root_data_dir if garage_install_all_users
        else (ansible_facts.env.HOME ~ '/.garage/data')
      }}
- name: Ensure Data Directories Exist
  ansible.builtin.file:
    state: directory
    owner: "{{ install_user }}"
    mode: "0755"
    path: "{{ item }}"
  loop:
    - "{{ metadata_dir }}"
    - "{{ data_dir }}"
- name: Create Garage Configuration
  ansible.builtin.template:
    src: garage.toml.jinja
    dest: "{{ config_file }}"
    mode: "0644"
    owner: "{{ install_user }}"
  notify:
    - Restart Garage S3
