---
- name: Create Garage Configuration
  ansible.builtin.template:
    src: garage.toml.jinja
    dest: "{{ config_file }}"
    mode: "0644"
    owner: "{{ install_user }}"
  notify:
    - Restart Garage S3
- name: Create Service
  block:
    - name: Ensure Service File Directory exists
      when: not garage_install_all_users
      ansible.builtin.file:
        path: "{{ ansible_facts.env.HOME }}/.config/systemd/user"
        mode: "0755"
        state: directory
    - name: Generate Service File
      ansible.builtin.template:
        dest: "{{ service_file }}"
        mode: "0644"
        src: garage.service.jinja
      notify:
        - Restart Garage S3
